export const FETCH_WEBINAR_START = 'FETCH_WEBINAR_START';
export const FETCH_WEBINAR_FAIL = 'FETCH_WEBINAR_FAIL';
export const FETCH_WEBINAR_SUCCESS = 'FETCH_WEBINAR_SUCCESS';

export const FETCH_BOOKINGS_START = 'FETCH_BOOKINGS_START';
export const FETCH_BOOKINGS_FAIL = 'FETCH_BOOKINGS_FAIL';
export const FETCH_BOOKINGS_SUCCESS = 'FETCH_BOOKINGS_SUCCESS';
export const CREATE_BOOKING_SUCCESS = 'CREATE_BOOKING_SUCCESS';
export const BOOKED_INIT = 'BOOKED_INIT';