# Generated by Django 3.1.7 on 2021-03-27 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'verbose_name_plural': 'Bookings'},
        ),
        migrations.AlterModelOptions(
            name='webinar',
            options={'verbose_name_plural': 'Webinars'},
        ),
        migrations.AlterField(
            model_name='webinar',
            name='cost',
            field=models.CharField(default=0, max_length=5),
        ),
    ]
